### PR TITLE
[Enhancements][Ezra] services and react optimization

### PR DESCRIPTION
**Pull request by ezerssss**
**Clickup Task:**
https://app.clickup.com/t/865curdwg

**Description:**
React Optimization and service fixes and optimizations

**Images/Videos:**
N/A

To Test just test if the app still functions ok.

### CODE REVIEW

**Comment by jedmamosto** [comment]
ill just approve siguro HAHAHAH

**Review by jedmamosto — COMMENTED** [review]
ay wait...

I get this error when I go to "Transactions"

``` ERROR  TypeError: Cannot read property 'title' of undefined

This error is located at:
    in Transactions (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider
    in NativeWind.SafeAreaProvider
    in Unknown (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
```

**Comment by jedmamosto** [comment]
Yep I think that's the only error I have. Checked everything from buying to selling and it seems good.

**Review by jedmamosto — APPROVED** [review]
Issues are resolved! Approved.

**Review by HansGabriel — APPROVED** [review]

**Pull request merged**
