### PR TITLE
[Adjustment] [Louie] Home Shadow

### PR DESCRIPTION
**Pull request by cezro**
**Clickup Task:**
https://app.clickup.com/t/865cqyte9

**Description:**
Shadow is too dark

**Images/Videos:**
image
image

### CODE REVIEW

**Review by ezerssss — APPROVED** [review]

**Review by jedmamosto — CHANGES_REQUESTED** [review]
Shadow looks too dark. Make it lighter:

image

**Comment by jedmamosto** [comment]
Possible solution might be making a custom shadow?

**Comment by cezro** [comment]
> Shadow looks too dark. Make it lighter:
> 
> image

image

**Comment by cezro** [comment]
> Also seeing these: (I'm not sure if it's significant pero yeah)
> 
> image

Although about this one, I really don't know what's causing this because even if iItried removing the shadows it still would persist.

**Review by jedmamosto — APPROVED** [review]
Better! GJ lou

Approved - will need one last approval from @caspted tho

**Review by caspted — CHANGES_REQUESTED** [review]
Screenshot 2023-07-20 at 11 42 51 PM

Make the shadow the same with the filter by college since that is ok naman (android)

**Review by HansGabriel — APPROVED** [review]

**Comment by jedmamosto** [comment]
Delete this PR nalang siguro no? @cezro @ezerssss

**Pull request closed without merging**
