### PR TITLE
[Adjustment] [Louie] Check these out Card iOS fix

### PR DESCRIPTION
**Pull request by cezro**
**Clickup Task:** https://app.clickup.com/t/865cqyt85

**Description:**
iOS check these out card shadow fix

**Images/Videos:**
image

### CODE REVIEW

**Review by jedmamosto — CHANGES_REQUESTED** [review]
Can you add shadows din to the "From the most trusted sellers" products? it has shadows too, forgot to mention

image

image

**Comment by cezro** [comment]
> Can you add shadows din to the "From the most trusted sellers" products? it has shadows too, forgot to mention
> 
> image
> 
> image

**Review by jedmamosto — APPROVED** [review]
Looks good! GJ lou

**Review by caspted — APPROVED** [review]
Looks good on android as well

**Pull request merged**
