### PR TITLE
[Adjustment] [Louie] Category Card Fix

### PR DESCRIPTION
**Pull request by cezro**
**Clickup Task:**
https://app.clickup.com/t/865cra8y0

**Description:**
Category Card Symmetry

**Images/Videos:**
https://github.com/ezerssss/unihub/assets/90561528/8e8bbc36-a4de-4f9a-b8ea-28e7ce53ed78

### CODE REVIEW

**Review by ezerssss — APPROVED** [review]

**Review by jedmamosto — APPROVED** [review]
LOOKS GOOD LOU! 

There's this bad UX but I guess it's not part of your task na so ill approve nalang

image


Good job!

**Comment by jedmamosto** [comment]
@caspted you can test then if goods na, you can approve

**Comment by jedmamosto** [comment]
ay @caspted put your comments here gali para the dev who'll take over can review and make changes for it

**Comment by jedmamosto** [comment]
maybe we can approve this lang anay tapos we just have the shadows issue be one big task nalang? ano sinyo? @ezerssss @caspted

**Review by caspted — APPROVED** [review]
Nice job on this task

**Pull request merged**
