### PR TITLE
[Enhancment][Hans] enhance transaction screen

### PR DESCRIPTION
**Pull request by HansGabriel**
**Clickup Task:**
https://app.clickup.com/t/865cr7r06

**Description:**
Fix certain UI issues

**Images/Videos:**
https://discord.com/channels/1112186342995136584/1119101722095267891/1136325587531731075

### CODE REVIEW

**Review by ezerssss — APPROVED** [review]

**Comment by jedmamosto** [comment]
Looks good nong, one last change nalang... the header still too close to the status bar - perhaps copy the "Sell" page header spacing?

**Comment by jedmamosto** [comment]
Goods on the spacing nong! Good job but I think @caspted will be the one to approve this so we make sure nga its also good sa android screen

**Comment by jedmamosto** [comment]
Ay nong, ang 'Order Requests' header pa gali @HansGabriel

**Review by caspted — CHANGES_REQUESTED** [review]
- (Android) would like to make changes to the spacing here for the your transaction heading the figma design has 110 margin on both sides

**Comment by jedmamosto** [comment]
don't take the Figma too literally ted HAHAHA pero it should just be centered anyway

**Comment by jedmamosto** [comment]
> * (Android) would like to make changes to the spacing here for the your transaction heading the figma design has 110 margin on both sides
>   

don't take the Figma too literally ted HAHAHA pero it should just be centered anyway (it seems centered to me)

**Review by caspted — APPROVED** [review]
Good job2 its looks good namn I forgot about different phones but it is centered.

**Pull request merged**
